App\Entity\Location:
     properties:
        city:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
        country:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
        coutry_code:
            - NotBlank: ~
            - Length:
                min: 1
                max: 2
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'

